name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install ubuntu package
      run: sudo apt-get install zip

    - name: Build scripts
      run: |
        npm ci
        npm run build

    - name: Build distributable
      run: |
        ls -al
        rm -rf dist && mkdir dist
        cp -r css dist/css
        cp -r js/build dist/js
        cp -r icons dist/icons
        cp -r options dist/ && mv dist/options/build/* dist/options/ && rmdir dist/options/build/
        cp manifest.json dist
        cp LICENSE dist
        cp db.json dist
        echo "const PROVISIONED_DB = `cat db.json`;" > dist/js/db.js
        npm run lint 2> lint.err
        [ -s lint.err ] && exit 1
        zip -r extension.crx dist && cp extension.crx dist

    - name: Commit report
      run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          git add -fN dist
          git diff -- dist ':(exclude)*.crx' > git.diff
          [ -s git.diff ] && git add -f extension.crx dist && git commit -m ":rocket: deploy" && git push || echo "Skip commit"
